### ISSUE TITLE
Research: Run AdsPower as a server in an Ubuntu server with no UI

### ISSUE THREAD

**Issue by leandrosardi** [connection-sphere/adspower-client#2]
## Research

Message to AdsPower support:

```
Hello,

I need to know how to:

1. Install AdsPower from bash/command line, in a server with no desktop/ui
2. Start AdsPower listener from bash/command line, in the same server no desktop/ui, 
3. And login to my AdsPower account from command line too;
4. And perform all operations like create profile, delete profile, start and stop profiles (in headless mode too) by calling the local API
```

Also, 

```
Another question:

5. Can I run AdsPower in different computers, under the same login?
```

**Comment by leandrosardi** [comment]
## Refereneces

- https://www.adspower.com/news/Local-API-and-Headless-Browsing

- DEB Package: https://version.adspower.net/software/linux-x64-global/AdsPower-Global-5.9.14-x64.deb

- How do I install a .deb file via the command line? --> https://askubuntu.com/questions/40779/how-do-i-install-a-deb-file-via-the-command-line

As per the article above, AdsPower meets with all our requirements:

1. :ok: Install AdsPower from bash/command line, in a server with no desktop/ui
2. :ok: Start AdsPower listener from bash/command line, in the same server no desktop/ui, 
3. :ok: And login to my AdsPower account from command line too;
4. :ok: And perform all operations like create profile, delete profile, start and stop profiles (in headless mode too) by calling the local API;
5. :ok: Can I run AdsPower in different computers, under the same login?

**Comment by leandrosardi** [comment]
## Tasks

1. :ok: Adapt library to run browsers in headless mode.
2. :ok: Setup AWS free-tier instance.
3. :ok: Install ChromeDriver.
4. :ok: Install AdsPower from bash.
5. :x: Run AdsPower listener from bash too, in headless mode.
6. :ok: Add bash scripts to the repository: `install.sh`, `start.sh`, `stop.sh`.

**Comment by leandrosardi** [comment]
> Run AdsPower listener from bash too, in headless mode.

## Problem


I need to run AdsPower App in HEADLESS mode, into a Ubuntu Server with no GUI.

When I run the command adspower_global` I get the error shown in the picture below.

![image](https://github.com/leandrosardi/adspower-client/assets/55877846/2aea2c56-7fe8-46ce-a9d2-a6e62766e42d)

My question is: Is it possible to run the APP in headless mode with out a Desktop (GUO) installed in the server?

**Comment by leandrosardi** [comment]
Commit [d00105bc82cf3f85c0ea6c794c245a61be6b16f6](https://github.com/leandrosardi/adspower-client/commit/d00105bc82cf3f85c0ea6c794c245a61be6b16f6) is related with this issue.

Updating documentation with Jarvis.

Jarvis, please perform these tasks:

```
1. find the adspower-client project in this local computer, right here: ~/code/adspower-client

2. read and understand the documentation of adspower-client in this local computer, here: ~/code/adspower-client/README.md

3. Find all changed done in the commit d00105bc82cf3f85c0ea6c794c245a61be6b16f6 in the folder of this local computer: ~/code/adspower-client

4. In the file of this local computer ~/code/adspower-client/README.md, add a new chapter "4. Headless", and explain the following topics with code examples in Ruby, following the source code in ~/code/adspower-client/lib/adspower-client.rb: 1) How to start AdsPower server using the start_server method, 2) How to stop AdsPower server using the stop_server method, 3) How to check if the server is running with the server_running? method, and 4) How to start a browser in headless mode passing false in the second parameter of the metod driver.

5. In the local file ~/code/adspower-client/README.md, in the outline section, add a link to chapter 4 please, right below of the link "3. Advanced"
```

**Comment by hamzaaitbrik** [comment]
Hello. Did you manage to run AdsPower on your headless server? I'm stuck in this exact issue. Thanks.

**Comment by leandrosardi** [comment]
> Hello. Did you manage to run AdsPower on your headless server? I'm stuck in this exact issue. Thanks.

@hamzaaitbrik Yes. It is well documented [here](https://github.com/MassProspecting/adspower-client#4-headless).

BTW, I will appreciate if you follow and add a star to this repository.

**Comment by damienaltman42** [comment]
Hello,

Thank you for all the information and the work you’ve shared here. I would like to use AdsPower on an Amazon EC2 instance with a Linux distribution running in headless mode (without a graphical interface). I followed the installation instructions and was able to launch the program, but I’m having trouble logging into my AdsPower account without a GUI.

Instance details:

	•	Platform: Amazon Linux (Linux/UNIX) kernel-6.1-x86_64

Here are the steps I followed:

	1.	Launched the EC2 instance with Amazon Linux in headless mode (no GUI).
	2.	Downloaded and installed the AdsPower package using dpkg.
	3.	Configured the environment for headless use.

However, I haven’t found a way to authenticate on AdsPower without the graphical interface. Could you provide the procedure or the necessary settings to connect in headless mode?

Thank you in advance for your help and for any additional support you can provide regarding the use of the local API in a headless environment.

**Comment by leandrosardi** [comment]
> Hello,
> 
> Thank you for all the information and the work you’ve shared here. I would like to use AdsPower on an Amazon EC2 instance with a Linux distribution running in headless mode (without a graphical interface). I followed the installation instructions and was able to launch the program, but I’m having trouble logging into my AdsPower account without a GUI.
> 
> Instance details:
> 
> ```
> •	Platform: Amazon Linux (Linux/UNIX) kernel-6.1-x86_64
> ```
> 
> Here are the steps I followed:
> 
> ```
> 1.	Launched the EC2 instance with Amazon Linux in headless mode (no GUI).
> 2.	Downloaded and installed the AdsPower package using dpkg.
> 3.	Configured the environment for headless use.
> ```
> 
> However, I haven’t found a way to authenticate on AdsPower without the graphical interface. Could you provide the procedure or the necessary settings to connect in headless mode?
> 
> Thank you in advance for your help and for any additional support you can provide regarding the use of the local API in a headless environment.

For starting AdsPower in headless mode, you have to first get an API key from the GUI.

For more infromation, refer to the [chapter 4 of the documentation](https://github.com/MassProspecting/adspower-client?tab=readme-ov-file#4-headless).

**Comment by hamzaaitbrik** [comment]
> Hello,
> 
> Thank you for all the information and the work you’ve shared here. I would like to use AdsPower on an Amazon EC2 instance with a Linux distribution running in headless mode (without a graphical interface). I followed the installation instructions and was able to launch the program, but I’m having trouble logging into my AdsPower account without a GUI.
> 
> Instance details:
> 
> ```
> •	Platform: Amazon Linux (Linux/UNIX) kernel-6.1-x86_64
> ```
> 
> Here are the steps I followed:
> 
> ```
> 1.	Launched the EC2 instance with Amazon Linux in headless mode (no GUI).
> 2.	Downloaded and installed the AdsPower package using dpkg.
> 3.	Configured the environment for headless use.
> ```
> 
> However, I haven’t found a way to authenticate on AdsPower without the graphical interface. Could you provide the procedure or the necessary settings to connect in headless mode?
> 
> Thank you in advance for your help and for any additional support you can provide regarding the use of the local API in a headless environment.

Like @leandrosardi said, working with AdsPower on headless mode requires an API key, not credentials.

I remember that I did it with one command on a headless Linux Ubuntu server. The command was `adspower_global --headless=true --api-key=apiKey --api-port=50325`. Replace apiKEY with your actual apiKey, and replace the port to one of your liking, I left it as is. Refer to [AdsPower's API documentation](https://help.adspower.com/docs/api) for more information.

**Comment by leandrosardi** [comment]
> > Hello,
> > Thank you for all the information and the work you’ve shared here. I would like to use AdsPower on an Amazon EC2 instance with a Linux distribution running in headless mode (without a graphical interface). I followed the installation instructions and was able to launch the program, but I’m having trouble logging into my AdsPower account without a GUI.
> > Instance details:
> > ```
> > •	Platform: Amazon Linux (Linux/UNIX) kernel-6.1-x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here are the steps I followed:
> > ```
> > 1.	Launched the EC2 instance with Amazon Linux in headless mode (no GUI).
> > 2.	Downloaded and installed the AdsPower package using dpkg.
> > 3.	Configured the environment for headless use.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, I haven’t found a way to authenticate on AdsPower without the graphical interface. Could you provide the procedure or the necessary settings to connect in headless mode?
> > Thank you in advance for your help and for any additional support you can provide regarding the use of the local API in a headless environment.
> 
> Like @leandrosardi said, working with AdsPower on headless mode requires an API key, not credentials.
> 
> I remember that I did it with one command on a headless Linux Ubuntu server. The command was `adspower_global --headless=true --api-key=apiKey --api-port=50325`. Replace apiKEY with your actual apiKey, and replace the port to one of your liking, I left it as is. Refer to [AdsPower's API documentation](https://help.adspower.com/docs/api) for more information.

@hamzaaitbrik.

This adspower-client gem resolves what you say with the `start_server` and `stop_server` methods.

For more infromation, refer to the [chapter 4 of the documentation](https://github.com/MassProspecting/adspower-client?tab=readme-ov-file#4-headless).

**Comment by andriibureviy** [comment]
Hey, could u help me resolve this kind of problem? 
<img width="507" alt="image" src="https://github.com/user-attachments/assets/c3c7cb37-22fc-4bdd-a337-5d075774c206">

**Comment by leandrosardi** [comment]
> Hey, could u help me resolve this kind of problem? <img alt="image" width="507" src="https://private-user-images.githubusercontent.com/84023934/386651259-c3c7cb37-22fc-4bdd-a337-5d075774c206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODY5NjgsIm5iZiI6MTczMTY4NjY2OCwicGF0aCI6Ii84NDAyMzkzNC8zODY2NTEyNTktYzNjN2NiMzctMjJmYy00YmRkLWEzMzctNWQwNzU3NzRjMjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE2MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTRhOWFlOWI0ODkyNTRhYzU1OTgyODVjMGY4NzM1ODc5Y2MzYmRmMGQ2ZjBiODVhNWYwN2JiMjg3YTZhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rnylMlwYblvcCGF0BAqQ2afcABI1m-rGf1NsRvNURXk">

The script below is working perfectly well for me:

```ruby
# Reference: https://github.com/MassProspecting/adspower-client/issues/2

require 'adspower-client'

# The following constants are defined in this file of secrets:
# ADSPOWER_API_KEY
# ADSPOWER_PORT
# PROFILE_ID
# HEADLESS
require_relative './config'

# create an adspower client
client = AdsPowerClient.new(
    key: ADSPOWER_API_KEY, 
    port: ADSPOWER_PORT,
    server_log: '~/foo.log',
)

# start the server
client.server_start if client.online? == false

# open the browser
driver = client.driver(PROFILE_ID, HEADLESS)

# visit google.com
driver.get('https://google.com')
puts driver.title
# => Google

# visit to https://mercadolibre.com
driver.get('https://mercadolibre.com')
puts driver.title
# => Mercado Libre - Envíos Gratis en el día

# close the browser
driver.quit

# stop the server
client.server_stop
```

My environment:

- Ubuntu 20.04
- Ruby 3.1.2
- AdsPower 6.9.24
- adspower-client gem 1.0.14

**Comment by leandrosardi** [comment]
I pushed an example:

[https://github.com/MassProspecting/adspower-client/blob/main/examples/headless.rb](https://github.com/MassProspecting/adspower-client/blob/main/examples/headless.rb)

**Comment by andriibureviy** [comment]
I have got some update, if I run on 
```
adspower_global --headless=true --api-key=API --api-port=50325 --no-sandbox
AdsPower run v6.10.20
```

And after running AdsPower via gem, everything is starting, the next question, how to download and install SunBrowser?
```

(myenv) root@ubuntu-16gb-hel1-1:~# ruby adspower_test.py
/root/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/adspower-client-1.0.14/lib/adspower-client.rb:133:in `block in start': Error: {"code"=>100027, "data"=>{"type"=>"chrome", "kernel"=>"128"}, "msg"=>"SunBrowser 128 is not ready,please to download!"} (RuntimeError)
        from /root/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/adspower-client-1.0.14/lib/adspower-client.rb:42:in `with_lock'
        from /root/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/adspower-client-1.0.14/lib/adspower-client.rb:128:in `start'
        from /root/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/adspower-client-1.0.14/lib/adspower-client.rb:172:in `driver'
        from adspower_test.py:29:in `<main>'
(myenv) root@ubuntu-16gb-hel1-1:~# 



```

**Comment by leandrosardi** [comment]
> next question, how to download and install SunBrowser?

Did you mean SunBrowser?

This is a question to ask to AdsPower's support.

**Comment by AndrejGorodnij** [comment]
@leandrosardi Actually official documentations doesn't contain instructions about it, only methods description.

I'm trying to start browser by user_id, but got:

`"SunBrowser 139 is not ready,please to download!"`

So we can't install it over API, because of system and users permissions. I'm running it on Linux server, so as I understand I need to open desktop app GUI, authorize, install browsers and only then run API...

So thats it - you can't use automation on Linux at ALL, even if you're using Desktop..

Official website note:
```
Note: SunBrowser 111 and later (Chromium-based versions) are only compatible with:

    Windows 10 and later
    Windows Server 2016 and later
    macOS 10.13 and later

```

**Comment by leandrosardi** [comment]
> [@leandrosardi](https://github.com/leandrosardi) Actually official documentations doesn't contain instructions about it, only methods description.
> 
> I'm trying to start browser by user_id, but got:
> 
> `"SunBrowser 139 is not ready,please to download!"`
> 
> So we can't install it over API, because of system and users permissions. I'm running it on Linux server, so as I understand I need to open desktop app GUI, authorize, install browsers and only then run API...
> 
> So thats it - you can't use automation on Linux at ALL, even if you're using Desktop..
> 
> Official website note:
> 
> ```
> Note: SunBrowser 111 and later (Chromium-based versions) are only compatible with:
> 
>     Windows 10 and later
>     Windows Server 2016 and later
>     macOS 10.13 and later
> ```

@AndrejGorodnij - This error means that you have to open your AdsPower terminal and install the browser version that you are trying to launch.

If it is a Chronium-based browser, you will need the correct version of ChromeDriver too.

**Comment by leandrosardi** [comment]
> So thats it - you can't use automation on Linux at ALL, even if you're using Desktop..

@AndrejGorodnij it is working perfectly well for me on Ubuntu 22.04.

I didn't try it on other distros / versions.

**Comment by AndrejGorodnij** [comment]
@leandrosardi hmm.. so why website says that browsers are not available on Linux at all? T_T

Can you give some links about "AdsPower terminal"... ? I'm saying that I have not any GUI on my Linux VPS, and can't call anything except Adspowe API routers... 

Would be great to read something about it. Thanks.

**Comment by leandrosardi** [comment]
> [@leandrosardi](https://github.com/leandrosardi) hmm.. so why website says that browsers are not available on Linux at all? T_T
> 
> Can you give some links about "AdsPower terminal"... ? I'm saying that I have not any GUI on my Linux VPS, and can't call anything except Adspowe API routers...
> 
> Would be great to read something about it. Thanks.

Hello @AndrejGorodnij ,

I have this AdsPower client running in50+ VPSs right now.
So,headless is a proven feature.

On the other hand, Right now I am in the middle of a project.
I can manage your question in one week or two.

If you need it with URGENCY, we can discuss a consultancy service (not expensive - don't worry).
